<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$template = $escape($this->partial('common/admin/card-grid-item'));
?>

<a href="#" class="collapse" aria-label="collapse">
    <h4><?= $translate('Cards') ?></h4>
</a>
<div class="attachments cards collapsible" data-template="<?= $template ?>">
    <button class="card-form-add" type="button"><?= $translate('Add card') ?></button>
    <?php foreach ($cards as $card) {
        echo $this->partial('common/admin/card-grid-item', ['card' => $card]);
    } ?>
</div>