<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

$template = $escape($this->partial('common/admin/column-layout-item'));
?>

<a href="#" class="collapse" aria-label="collapse">
    <h4><?= $translate('Columns') ?></h4>
</a>
<div class="attachments columns collapsible" data-template="<?= $template ?>">
    <button class="column-html-form-add" type="button"><?= $translate('Add HTML column') ?></button>
    <?php foreach ($columns as $column) {
        echo $this->partial('common/admin/column-layout-item', ['column' => $column]);
    } ?>
</div>