<?php
$translate = $this->plugin('translate');
?>

<div class="attachment">
    <span class="sortable-handle"></span>
    <div class="asset-title">HTML column</div>

    <ul class="actions">
        <li><a class="column-html-form-edit o-icon-configure button" title="<?= $translate('Open asset options') ?>" aria-label="<?= $translate('Open asset options') ?>"></a></li>
        <li class="delete"><a class="o-icon-delete button" title="<?= $translate('Delete attachment') ?>" href="#" aria-label="<?= $translate('Delete attachment') ?>"></a></li>
        <li class="undo"><a class="o-icon-undo button" title="<?= $translate('Restore attachment') ?>" href="#" aria-label="<?= $translate('Restore attachment') ?>"></a></li>
    </ul>
    
    <input type="hidden" data-sidebar-id="column-html-data-html" name="o:block[__blockIndex__][o:data][columns][__attachmentIndex__][html]" value="<?= $column['html'] ?? '' ?>">
</div>