<?php
use \Omeka\Api\Exception\NotFoundException;

$translate = $this->plugin('translate');
$this->headLink()->appendStylesheet($this->assetUrl('css/item-form.css', 'PageBlocks'));
$this->headScript()->appendFile($this->assetUrl('js/item-form.js', 'PageBlocks'));

$item = null;
$itemId = $element->getValue();
if ($itemId) {
    try {
        $item = $this->api()->read('items', $itemId)->getContent();
    } catch (NotFoundException $exception) {
        $element->setValue(null);
    }
}
?>
<div class="item-form-element<?php if (!$item) echo ' empty'; ?>">
    <?php if ($item): ?>
        <span class="selected-item">
            <img class="selected-item-image"
                src="<?= $item->primaryMedia()->thumbnailUrl() ?>"
            />
            <div class="selected-item-name">
                <?= $item->title() ?>
            </div>
        </span>
    <?php else: ?>
        <span class="selected-item">
            <img class="selected-item-image" />
            <div class="selected-item-name"></div>
        </span>
    <?php endif; ?>
    <span class="no-selected-item">
        <?php echo $translate('[No item selected]'); ?>
    </span>
    <button type="button" class="item-form-select" data-sidebar-content-url="<?php echo $this->escapeHtml($this->url('admin/default', ['controller' => 'item', 'action' => 'sidebar-select'])); ?>">
        <?php echo $translate('Select'); ?>
    </button>
    <button type="button" class="item-form-clear red button">
        <?php echo $translate('Clear'); ?>
    </button>
    <div class="attachments-form attachments-item-only" style="display: none;"></div>
    <?php echo $this->formHidden($element); ?>
</div>