<?php
$translate = $this->plugin('translate');

if (!empty($resourceFields)) {
    $resolvedResources = [];

    foreach ($resourceFields as $resourceField => $resourceType) {
        // Maintain blank values as default to trigger a form reset
        $resourceValues = [
            'type' => $resourceType,
            'filename' => '',
            'url' => ''
        ];

        if (!empty($values[$resourceField])) {
            $resource = $this->api()->read($resourceType . 's', $values[$resourceField])->getContent();
        }
                
        if (!empty($resource)) {
            if ($resourceType == "asset") {
                $resourceValues['filename'] = $resource->filename();
                $resourceValues['url'] = $resource->assetUrl();
            } else if ($resourceType == "item") {
                $resourceValues['filename'] = $resource->title();
                $resourceValues['url'] = $resource->primaryMedia()->thumbnailUrl('image/jpeg');
            }
            unset($resource);
        }

        $resolvedResources[$resourceField] = $resourceValues;
    }
}

$label = '';
if (!empty($values)) {
    if (is_callable($labelField)) {
        $label = $labelField($values);
    } else {
        $label = $values[$labelField] ?? '';
    }
}
?>

<div class="attachment">
    <span class="sortable-handle"></span>
    <?php if (!empty($iconField)): ?>
        <div class="thumbnail fa <?= $values[$iconField] ? "fa-" . $values[$iconField] : "fa-question unspecified"; ?>" aria-hidden="true"></div>
    <?php endif; ?>
    <div class="asset-title"><?= $label ?></div>

    <ul class="actions">
        <li><a class="<?= $sidebarId ?>-form-edit o-icon-configure button" title="<?= $translate('Open attachment options') ?>" aria-label="<?= $translate('Open attachment options') ?>"></a></li>
        <li class="delete"><a class="o-icon-delete button" title="<?= $translate('Delete attachment') ?>" href="#" aria-label="<?= $translate('Delete attachment') ?>"></a></li>
        <li class="undo"><a class="o-icon-undo button" title="<?= $translate('Restore attachment') ?>" href="#" aria-label="<?= $translate('Restore attachment') ?>"></a></li>
    </ul>
    
    <?php foreach ($keys as $key): ?>
        <input
            type="hidden"
            data-sidebar-id="<?= $sidebarId . "-data-" . str_replace("_", "-", $key); ?>"
            name="o:block[__blockIndex__][o:data][<?= $groupKey ?>][__attachmentIndex__][<?= $key ?>]"
            value="<?= $values[$key] ?? '' ?>"
            <?php foreach ($resolvedResources[$key] ?? [] as $resourceKey => $resourceValue): ?>
                data-resource-<?= $resourceKey ?>="<?= $resourceValue ?>"
            <?php endforeach; ?>
        />
    <?php endforeach; ?>
</div>