<?php

$assetUrl = $this->plugin('assetUrl');
$this->headLink()->appendStylesheet($assetUrl('css/style.css', 'PageBlocks'));

?>

<section class="col-container">
    <?php if ($header): ?>
        <h2><?= $header ?></h2>
    <?php endif; ?>
    <?php foreach ($columns as $column): ?>
        <div class="col-single">
            <?= $column["html"] ?>
        </div>
    <?php endforeach; ?>
</section>
